apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-backend
  name: test-backend
  namespace: backend
spec:
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers:
      - name: test-backend
        image: 437319709631.dkr.ecr.us-east-1.amazonaws.com/test-backend:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://test-deployment-db.cfaapgkmyph8.us-east-1.rds.amazonaws.com:3306/hobbie_backend_db?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=Europe/Paris
        - name: SPRING_DATASOURCE_USERNAME
          value: test-db-user
        - name: SPRING_DATASOURCE_PASSWORD
          value: Password1
---
apiVersion: v1
kind: Service
metadata:
  name: test-backend-service
  namespace: backend
  labels:
    run: test-backend-service
spec:
  type: ClusterIP
  ports:
  - name: test-backend-port
    port: 8080
    protocol: TCP
  selector:
    app: test-backend